
# SEO settings
title: "Vie"
description: ""
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: https://blog.yangchenzhong.cn # site url
enforce_ssl: blog.yangchenzhong.cn
# baseurl: "/" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

language: zh-CN

google_analytics: UA-75139334-2
repo: http://github.com/yangchenzhong/blog
disqus_shortname: "yangchenzhong"
twitter_username: "unlockyang"
comments: true

# Build settings
permalink   : /:title
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Vie"
  job      : "R&D Software Engineer"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : yangchenzhong@gmail.com
  url      : http://about.yangchenzhong.cn
  github   : http://github.com/yangchenzhong
  twitter  : http://twitter.com/unlockyang
  facebook : https://www.facebook.com/yangchenzhong
  linkedin : http://linkedin.com/in/yangchenzhong

# social settings
og_locale: "zh_CN"
twitter_card: "summary_large_image"
twitter_site: "@yangchenzhong"

# mul languages
languages:          ['en', 'cn']
language_default:   'cn'

date_format: YYYY-MM-DD
time_format: HH:mm:ss


gems:
  - bourbon
  - jekyll-paginate
  - jekyll-multiple-languages

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]


